---
- name: Install pcp
  yum: name=pcp state=installed
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Enable and start collector and listener
  service: name={{ item }} state=started enabled=yes
  with_items:
   - pmcd
   - pmlogger

- name: Deploy template
  template:
    src: templates/local.j2
    dest: /etc/pcp/pmlogger/control.d/local
    owner: root
    group: root
    mode: 0644
  notify: restart pmlogger
  when: pcp_logging_interval is defined
